apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: dapp
  name: dapp  # This should be indented under metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/docker-ethereum-default: "true"
        io.kompose.service: dapp
    spec:
      containers:
      - image: schadokar/eth-server:1.0.0
        name: dapp
        ports:
        - containerPort: 4000
          hostPort: 4000
          protocol: TCP
        env:
        - name: NODE_PORT
          valueFrom:
            configMapKeyRef:
              name: node-app-config
              key: NODE_PORT
        resources:
          requests:
          limitas:
          memory:128mi
          cpu:500m
          
            memory:  64mi
            cpu: 250m
      restartPolicy: Always
