apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react
  minReplicas: 1
  maxReplicas: 5 # Adjust based on your requirements
  targetCPUUtilizationPercentage: 50